// react-admin/src/layouts/sider/components/userinfo.jsx
import React from "react";
import { Avatar, Col, Row, Typography, Tooltip } from "antd";

export default function Userinfo() {
  const { Text, Title } = Typography;
  return (
    <Row className="ant-layout-sider-userinfo" wrap={false}>
      <Col flex="60px">
        <Tooltip title="点击修改个人信息" placement="bottomLeft">
          <Avatar size={50}>管理</Avatar>
        </Tooltip>
      </Col>
      <Col flex="auto">
        <Title
          level={5}
          className="username"
          ellipsis={{
            tooltip: true,
          }}
        >
          Admin
        </Title>
        <Text
          className="nickname"
          ellipsis={{
            tooltip: true,
          }}
        >
          超级管理员
        </Text>
      </Col>
    </Row>
  );
}

// ant-admin/src/layouts/sider/components/userinfo.vue
<template>
  <a-col flex="70px" style="text-align: center">
    <a-avatar :size="50" trigger-type="mask" @click="() => {}">
      <template #trigger-icon>
        <i class="ri-edit-line" style="color: var(--color-white)"></i>
      </template>
      {{ userStore.getFirstNickname }}
    </a-avatar>
  </a-col>
  <a-col flex="auto">
    <a-typography-paragraph
      :ellipsis="{
        showTooltip: true,
      }"
      class="username"
    >
      {{ userStore.username }}
    </a-typography-paragraph>
    <a-typography-paragraph
      :ellipsis="{
        showTooltip: true,
      }"
      class="nickname"
    >
      {{ userStore.nickname }}
    </a-typography-paragraph>
  </a-col>
</template>

<script setup>
import { useUser } from "@/store/admin/user.js";

const userStore = useUser();
</script>
