// react-admin/src/layouts/sider/index.jsx
import React from "react";
import { Layout, theme, Button, Col, Row, Space, Divider, Menu } from "antd";
import { useThemeStore } from "@/store/theme";
import Userinfo from "./components/userinfo";

function getItem(label, key, icon, children, type) {
  console.log({
    key,
    icon,
    children,
    label,
    type,
  });
  return {
    key,
    icon,
    children,
    label,
    type,
  };
}
const items = [
  getItem("Option 1", "1", ""),
  getItem("Option 2", "2", ""),
  getItem("Option 3", "3", ""),
  getItem("Navigation One", "sub1", "", [
    getItem("Option 5", "5", ""),
    getItem("Option 6", "6", ""),
    getItem("Option 7", "7", ""),
    getItem("Option 8", "8", ""),
  ]),
  getItem("Navigation Two", "sub2", "", [
    getItem("Option 9", "9", ""),
    getItem("Option 10", "10", ""),
    getItem("Submenu", "sub3", null, "", [
      getItem("Option 11", "11", ""),
      getItem("Option 12", "12", ""),
    ]),
  ]),
  getItem("Navigation Two", "sub2", "", [
    getItem("Option 9", "9", ""),
    getItem("Option 10", "10", ""),
    getItem("Submenu", "sub3", null, "", [
      getItem("Option 11", "11", ""),
      getItem("Option 12", "12", ""),
    ]),
  ]),
  getItem("Navigation Two", "sub2", "", [
    getItem("Option 9", "9", ""),
    getItem("Option 10", "10", ""),
    getItem("Submenu", "sub3", null, "", [
      getItem("Option 11", "11", ""),
      getItem("Option 12", "12", ""),
    ]),
  ]),
  getItem("Navigation Two", "sub2", "", [
    getItem("Option 9", "9", ""),
    getItem("Option 10", "10", ""),
    getItem("Submenu", "sub3", null, "", [
      getItem("Option 11", "11", ""),
      getItem("Option 12", "12", ""),
    ]),
  ]),
  getItem("Navigation Two", "sub2", "", [
    getItem("Option 9", "9", ""),
    getItem("Option 10", "10", ""),
    getItem("Submenu", "sub3", null, "", [
      getItem("Option 11", "11", ""),
      getItem("Option 12", "12", ""),
    ]),
  ]),
  getItem("Navigation Two", "sub2", "", [
    getItem("Option 9", "9", ""),
    getItem("Option 10", "10", ""),
    getItem("Submenu", "sub3", null, "", [
      getItem("Option 11", "11", ""),
      getItem("Option 12", "12", ""),
    ]),
  ]),
  getItem("Navigation Two", "sub2", "", [
    getItem("Option 9", "9", ""),
    getItem("Option 10", "10", ""),
    getItem("Submenu", "sub3", null, "", [
      getItem("Option 11", "11", ""),
      getItem("Option 12", "12", ""),
    ]),
  ]),
];
export default function Sider() {
  const { Sider } = Layout;
  const { token } = theme.useToken();
  const { darkTheme, switchTheme, showSider } = useThemeStore();

  return (
    <Sider
      theme="light"
      width={230}
      collapsed={showSider}
      collapsedWidth={0}
      style={{ background: token.colorBgContainer }}
    >
      <Space direction="vertical" className="ant-layout-space">
        <Userinfo />
        <Row className="ant-layout-sider-button" wrap={false}>
          <Col flex="auto">
            <Button type="text" icon={<i className="ri-apps-line"></i>} />
          </Col>
          <Col flex="10px">
            <Divider type="vertical" />
          </Col>
          <Col flex="auto">
            <Button
              type="text"
              onClick={() => switchTheme(!darkTheme)}
              icon={<i className={darkTheme ? "ri-sun-fill" : "ri-moon-fill"}></i>}
            />
          </Col>
          <Col flex="10px">
            <Divider type="vertical" />
          </Col>
          <Col flex="auto">
            <Button type="text" icon={<i className="ri-refresh-line"></i>} />
          </Col>
          <Col flex="10px">
            <Divider type="vertical" />
          </Col>
          <Col flex="auto">
            <Button type="text" icon={<i className="ri-logout-box-line"></i>} />
          </Col>
        </Row>
        <Divider className="ant-layout-sider-divider" />
        <Menu
          className="ant-layout-sider-menu"
          defaultSelectedKeys={["1"]}
          defaultOpenKeys={["sub1"]}
          mode="inline"
          items={items}
        />
      </Space>
    </Sider>
  );
}

// ant-admin/src/layouts/sider/index.vue
<template>
  <div class="ant-layout-sider-system">
    <a-space direction="vertical" :size="10" style="width: 100%">
      <a-row style="flex-flow: row nowrap">
        <Userinfo />
      </a-row>
      <a-row style="align-items: center">
        <a-col flex="auto" style="text-align: center">
          <a-tooltip content="切换系统应用" position="tl">
            <a-button type="text" @click="showApps">
              <template #icon>
                <i
                  :class="currentApp?.icon || 'ri-apps-line'"
                  :style="{
                    color: 'rgb(var(--primary-6))',
                  }"
                  v-if="menuStore.showApps"
                ></i>
                <i :class="currentApp?.icon || 'ri-apps-line'" v-else></i>
              </template>
            </a-button>
          </a-tooltip>
        </a-col>
        <a-col flex="10px">
          <a-divider type="vertical" margin="4.5px" />
        </a-col>
        <a-col flex="auto" style="text-align: center">
          <a-tooltip
            :content="themeStore.getTheme ? '切换亮色模式' : '切换暗黑模式'"
            position="tl"
          >
            <a-button type="text" @click="themeStore.switchTheme()">
              <template #icon>
                <i
                  class="ri-moon-fill"
                  style="color: #fff"
                  v-if="themeStore.getTheme"
                ></i>
                <i class="ri-sun-fill" style="color: #000" v-else></i>
              </template>
            </a-button>
          </a-tooltip>
        </a-col>
        <a-col flex="10px">
          <a-divider type="vertical" margin="4.5px" />
        </a-col>
        <a-col flex="auto" style="text-align: center">
          <a-tooltip content="清楚缓存" position="tl">
            <a-button type="text" @click="userStore.setAccessToken()">
              <template #icon>
                <i class="ri-refresh-line"></i>
              </template>
            </a-button>
          </a-tooltip>
        </a-col>
        <a-col flex="10px">
          <a-divider type="vertical" margin="4.5px" />
        </a-col>
        <a-col flex="auto" style="text-align: center">
          <a-tooltip content="注销登录" position="tl">
            <a-button type="text" @click="userStore.logout()">
              <template #icon>
                <i class="ri-logout-box-line"></i>
              </template>
            </a-button>
          </a-tooltip>
        </a-col>
      </a-row>
    </a-space>
    <a-divider />
  </div>
  <div class="ant-layout-sider-menu">
    {{ menuStore.getSelectedKeys }}
    <a-menu
      mode="inline"
      :inlineIndent="22"
      :level-indent="10"
      accordion
      auto-open-selected
      :selectedKeys="[menuStore.getSelectedKeys]"
      @click="tabsStore.switchTab"
    >
      <sider-menu
        :menus="menuStore.currentMenus"
        v-if="menuStore.currentMenus !== undefined"
      />
      <a-empty v-else />
    </a-menu>
  </div>
  <div class="footer-copyright">
    <span>&copy;{{ new Date().getFullYear() }}&nbsp;</span>
    <a :href="config.copyrightUrl" target="_blank">
      {{ config.copyrightTitle }}
    </a>
  </div>
</template>

<script setup>
import { ref, watch } from 'vue';
import config from '@/config';
import Userinfo from './components/userinfo.vue';
import SiderMenu from './components/sider-menu.vue';
import { useUser } from '@/store/admin/user.js';
import { useMenu } from '@/store/admin/menu.js';
import { useTabs } from '@/store/admin/tabs.js';
import { useTheme } from '@/store/admin/theme.js';

const userStore = useUser();
const menuStore = useMenu();
const tabsStore = useTabs();
const themeStore = useTheme();

const showApps = () => {
  menuStore.showApps = !menuStore.showApps;
  if (menuStore.showApps) {
    menuStore.currentMenus = menuStore.menus;
    menuStore.currentMenuKey = menuStore.selectedKeys;
    menuStore.selectedKeys = menuStore.currentAppId;
  } else {
    menuStore.currentMenus = menuStore.getCurrentMenus;
    menuStore.selectedKeys = menuStore.currentMenuKey;
  }
};

const currentApp = ref(menuStore.getMenu(menuStore.getCurrentAppId));

watch(
  () => menuStore.getCurrentAppId,
  () => {
    currentApp.value = menuStore.getMenu(menuStore.getCurrentAppId);
  }
);
</script>

<style scoped>
.ant-menu-inline {
  border-inline-end: 0px;
}
</style>
