// react-admin/src/layouts/header/index.jsx
import React from "react";
import { Layout, Col, Row, theme, Button } from "antd";
import { useThemeStore } from "@/store/theme";
import fullscreen from "@/utils/functions/fullscreen.js";

export default function Header() {
  const { Header } = Layout;
  const { token } = theme.useToken();
  const { showSider, switchShowSider } = useThemeStore();

  return (
    <Header style={{ background: token.colorBgContainer }}>
      <Row>
        <Col span={12}>
          <div className="header-custom-box">
            <Button
              type="text"
              onClick={() => switchShowSider()}
              icon={
                <i
                  className={
                    showSider ? "ri-menu-unfold-line" : "ri-menu-fold-line"
                  }
                ></i>
              }
            />
          </div>
        </Col>
        <Col span={12} className="header-custom-right">
          <div className="header-custom-box">
            <Button
              type="text"
              onClick={() => fullscreen.toggle()}
              icon={
                <i
                  className={
                    fullscreen.isFullscreen
                      ? "ri-fullscreen-exit-line"
                      : "ri-fullscreen-line"
                  }
                ></i>
              }
            />
          </div>
        </Col>
      </Row>
    </Header>
  );
}

// ele-admin/src/layouts/header/index.vue
<template>
  <el-row class="header-custom">
    <el-col :span="12">
      <div class="header-custom-box">
        <el-button type="text" @click="themeStore.switchShowSider()">
          <template #icon>
            <i class="ri-menu-fold-line" v-if="themeStore.showSider"></i>
            <i class="ri-menu-unfold-line" v-else></i>
          </template>
        </el-button>
      </div>
    </el-col>
    <el-col :span="12" class="header-custom-right">
      <div class="header-custom-box">
        <el-tooltip :content="isFullscreen ? '退出全屏' : '全屏'" position="br">
          <el-button type="text" @click="fullscreen.toggle()">
            <template #icon>
              <i class="ri-fullscreen-exit-line" v-if="isFullscreen"></i>
              <i class="ri-fullscreen-line" v-else></i>
            </template>
          </el-button>
        </el-tooltip>
      </div>
    </el-col>
  </el-row>
</template>

<script setup>
import { ref } from "vue";
import { useTheme } from "@/store/admin/theme.js";
import fullscreen from "@/utils/fullscreen.js";

const themeStore = useTheme();

const isFullscreen = ref();

fullscreen.on("change", () => {
  isFullscreen.value = fullscreen.isFullscreen;
});
</script>
